// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_produtos.Data;

#nullable disable

namespace backend_produtos.Migrations
{
    [DbContext(typeof(ProdutosDbContext))]
    [Migration("20260817194423_AddDemoProductSeedData")]
    partial class AddDemoProductSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend_produtos.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("backend_produtos.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("Saldo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Codigo = "P001",
                            Descricao = "Notebook Industrial",
                            Preco = 4500.00m,
                            Saldo = 15
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Codigo = "P002",
                            Descricao = "Monitor 24\"",
                            Preco = 900.00m,
                            Saldo = 30
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Codigo = "P003",
                            Descricao = "Teclado Mecânico",
                            Preco = 250.00m,
                            Saldo = 50
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Codigo = "P004",
                            Descricao = "Mouse Wireless",
                            Preco = 120.00m,
                            Saldo = 80
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Codigo = "P005",
                            Descricao = "SSD NVMe 1TB",
                            Preco = 480.00m,
                            Saldo = 40
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Codigo = "P006",
                            Descricao = "Placa de Vídeo",
                            Preco = 2800.00m,
                            Saldo = 12
                        });
                });

            modelBuilder.Entity("backend_produtos.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("backend_produtos.Models.Produto", "Produto")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("backend_produtos.Models.Produto", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
